---
assembly: /path/to/assembly.fasta
existing_meryl_database_path: /path/to/database.meryl

name_of_subtracted_meryl_database: to_find_minus_to_remove.meryl
#bed_file_of_putative_introgressed_regions: /panfs/jay/groups/7/hsiehph/gordo893/samples/PNG16/verkko1.4.1/align_against_hg38/hap1_for_rustybam/introgressed_regions/regions_in_PNG16.bed
bed_file_of_putative_introgressed_regions: fake_introgressed.bed
